name: car_ai_app
description: A new Flutter project.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  share_plus: ^7.2.1
  path_provider: ^2.1.2
  flutter_svg: ^2.0.9 