steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/car-ai-app', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/car-ai-app']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'car-ai-app'
  - '--image'
  - 'gcr.io/$PROJECT_ID/car-ai-app'
  - '--region'
  - 'northamerica-northeast1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated' 